# Generated by Django 3.2.7 on 2021-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211002_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About me'},
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
